"""add pearls column to users

Revision ID: 4b8b6dbb3a66
Revises: 
Create Date: 2026-03-01 01:00:52.172891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b8b6dbb3a66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pearl_balances, owned_items 관련 drop 코드는 테이블이 이미 없으므로 제거
    # pearls 컬럼이 이미 존재하므로 추가하지 않음
    op.add_column('users', sa.Column('pearls', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pearls')
    op.create_table('owned_items',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('item_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='owned_items_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_owned_items_user_id', 'owned_items', ['user_id'], unique=False)
    op.create_table('pearl_balances',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('pearls', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pearl_balances_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_pearl_balances_user_id', 'pearl_balances', ['user_id'], unique=False)
    # ### end Alembic commands ###
